"""
Django settings for scoring_sys_bknd project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from django.template.defaultfilters import default
from mongoengine import connect
import environ
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Import .env configuration file
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# MongoEngine connection
connect(
    db=env("DB_NAME"),
    host=f"mongodb+srv://{env('DB_USER')}:{env('DB_PASSWORD')}@{env('DB_ENHOST')}/{env('DB_NAME')}?retryWrites=true&w=majority",
    alias="default"
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEVELOPMENT")

ALLOWED_HOSTS = env.list("HOSTS")


# Application definition

INSTALLED_APPS = [
    # Django Core Modules
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party security apps
    'corsheaders',           # CORS protection
    'axes',                  # Brute-force login protection
    'django_user_agents',    # User-agent detection

    # REST API
    'rest_framework',

    # Modules
    'users',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # AxesStandaloneBackend should be first
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    # Security headers
    "django.middleware.security.SecurityMiddleware",

    # CORS (must be near top)
    "corsheaders.middleware.CorsMiddleware",

    # Session + Auth
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    # Brute-force login protection
    "axes.middleware.AxesMiddleware",

    # Standard Django middleware
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    # Extra security headers
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Device/user-agent detection
    "django_user_agents.middleware.UserAgentMiddleware",
]

# CORS & COOKIE CONFIGURATIONS

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-csrftoken'
]

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Strict"

ROOT_URLCONF = 'scoring_sys_bknd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scoring_sys_bknd.wsgi.application'

# Database
# Django's relational database settings are intentionally left empty because
# MongoEngine manages the MongoDB connection separately above.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ADDITIONAL SECURITY SETTINGS

# SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT")
# SECURE_CONTENT_TYPE_NOSNIFF = True

if DEBUG is False:
    SECURE_HSTS_SECONDS = 31536000     # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

